spring.application.name=calendario-api
spring.datasource.url=jdbc:postgresql://work-calendar-db.c2hu4ugaiomu.us-east-1.rds.amazonaws.com:5432/calendar
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=testuser
spring.datasource.password=pass123
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
festivos.api.url=${API_FESTIVOS_URL:http://localhost:3000/festivos/obtener/}

logging.level.org.hibernate.SQL=DEBUG